version: '3'
services:
  redis:
    image: redis
    ports: 
      - "5001:6379"
  web:
    depends_on: 
      - redis
    image: dockergkz/projectdevops:latest
    build: .
    ports:
      - "5000:3000"
    environment:
      REDIS_HOST: redis
