apiVersion: v1
kind: Service
metadata:
  name: nodejs-services
spec:
  type: NodePort
  selector:
    app: nodejs-app
  ports:
    - port: 3000
      nodePort: 30001

---

apiVersion: v1
kind: Service
metadata:
  name: redis-services
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379



