version: '3'
services:
  redis:
    image: redis
    volumes:
      - .:/data

  web:
    # COMPLETE HERE
    depends_on: 
      - redis
    image: myimage:latest
    build: .
    ports:
      - "5000:8080"
    environment:
      REDIS_HOST: redis

      